//
// @depletionmode 2019
//

#pragma once

#define SME_IOCTL_GET_CAPABILITIES CTL_CODE(FILE_DEVICE_UNKNOWN, 0xa80, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _SME_GET_CAPABILITIES_RESPONSE {
    BOOLEAN Supported;
    ULONG PageTableCbitIdx;
    ULONG PhysicalAddressSpaceReduction;
    BOOLEAN MemoryEncryptionModeEnabled;

} SME_GET_CAPABILITIES_RESPONSE, *PSME_GET_CAPABILITIES_RESPONSE;

#define SME_IOCTL_ALLOCATE CTL_CODE(FILE_DEVICE_UNKNOWN, 0xa81, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _SME_ALLOCATE_REQUEST {
    SIZE_T Size;

} SME_ALLOCATE_REQUEST, *PSME_ALLOCATE_REQUEST;

typedef struct _SME_ALLOCATE_RESPONSE {
    PVOID Address;

} SME_ALLOCATE_RESPONSE, *PSME_ALLOCATE_RESPONSE;

#define SME_IOCTL_FREE CTL_CODE(FILE_DEVICE_UNKNOWN, 0xa82, METHOD_BUFFERED, FILE_ANY_ACCESS)

typedef struct _SME_FREE_REQUEST {
    PVOID Address;

} SME_FREE_REQUEST, *PSME_FREE_REQUEST;
